name: Test Email Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: 24f3004545@ds.study.iitm.ac.in
        run: echo "Hello, world!"
